In [2]:
import pandas as pd

# Price data

In [ ]:

price = pd.read_parquet("https://drive.google.com/file/d/1In0phmpmTLejavhAz8MsdhfPPDXPz0gM/view?usp=drive_link")

target_countries = ['Kenya', 'Ethiopia', 'Somalia']
print("Unique countries in price DataFrame:", price['country'].unique())
target_countries_df = price[price['country'].isin(target_countries)]
target_countries_df.head()

In [ ]:
if csv_path:
    df = pd.read_csv(csv_path)
    target_countries = ['Kenya', 'Ethiopia', 'Somalia']
    target_countries_df = df[df['country'].isin(target_countries)]
    target_countries_df.head()

In [ ]:
if 'target_countries_df' in locals():
    final = target_countries_df[['year', 'month','country', 'ISO3', 'adm1_name','adm2_name', 'mkt_name', 'lat', 'lon','year', 'month', 'currency','c_sorghum']].head()
    display(final.head())

In [ ]:
if 'final' in locals():
    final.head()

# Population data

In [ ]:
# Read Kenya Population Data
# We'll try multiple paths to be sure

ken_pop = '../../data/population/ken_admpop_2019.xlsx'
meta_ken_pop ='../../data/population/ken_adminboundaries_tabulardata.xlsx'
xls = pd.ExcelFile(ken_pop)
meta_ken_pop_xls = pd.ExcelFile(meta_ken_pop)
ken_pop_df = pd.read_excel(xls, sheet_name ='ken_admpop_ADM2_2019')
ken_pop_boundary = pd.read_excel(meta_ken_pop_xls, sheet_name = 'ADM2')
ken_pop_df
#성별 & 나이로 disaggregate 한거임

,ADM0_NAME,ADM0_PCODE,ADM1_NAME,ADM1_PCODE,ADM2_NAME,F_TL,M_TL,T_TL,F_00_04,F_05_09,...,T_60_64,T_65_69,T_70_74,T_75_79,T_80_84,T_85_89,T_90_94,T_95_99,T_100Plus,T_Unstated
0,Kenya,KE,Mombasa,KE001,Changamwe,63121,68761,131882,7287,6717,...,1546,956,494,188,132,44,30,14,7,1
1,Kenya,KE,Mombasa,KE001,Jomvu,80410,83002,163412,10388,9602,...,1749,1081,597,246,125,68,39,15,9,4
2,Kenya,KE,Mombasa,KE001,Kisauni,145176,146748,291924,18776,16505,...,3361,2130,1233,582,335,174,65,40,22,3
3,Kenya,KE,Mombasa,KE001,Likoni,123392,126962,250354,16757,14291,...,2569,1560,853,396,239,99,32,18,11,5
4,Kenya,KE,Mombasa,KE001,Mvita,78601,75565,154166,7566,7399,...,3831,2729,1979,1052,697,269,102,44,14,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
340,Kenya,KE,Nairobi,KE047,Makadara,93157,96369,189526,9833,8543,...,2221,1480,949,389,198,95,38,18,10,3
341,Kenya,KE,Nairobi,KE047,Mathare,100028,106522,206550,12761,10482,...,1800,1065,529,184,109,47,18,12,4,3
342,Kenya,KE,Nairobi,KE047,Njiru,318809,307642,626451,39760,34782,...,5522,3045,1773,726,425,223,105,66,28,23
343,Kenya,KE,Nairobi,KE047,Starehe,101238,109173,210411,10035,8588,...,2696,1684,1022,489,262,112,43,19,10,9
344,Kenya,KE,Nairobi,KE047,Westlands,155021,153818,308839,14289,12930,...,6668,4804,3384,1904,1243,654,208,92,23,10

In [9]:
ken_pop_boundary

,ADM2_EN,ADM2_PCODE,ADM2_REF,ADM2ALT1_EN,ADM2ALT2_EN,ADM1_EN,ADM1_PCODE,ADM0_EN,ADM0_PCODE,DATE,VALIDON,VALIDTO,AREA_SQKM
0,Ainabkoi,KE027144,NaN,NaN,NaN,Uasin Gishu,KE027,Kenya,KE,2017-11-03,2019-10-31,NaN,502.561920
1,Ainamoi,KE035190,NaN,NaN,NaN,Kericho,KE035,Kenya,KE,2017-11-03,2019-10-31,NaN,245.644440
2,Aldai,KE029152,NaN,NaN,NaN,Nandi,KE029,Kenya,KE,2017-11-03,2019-10-31,NaN,467.744263
3,Alego Usonga,KE041234,NaN,NaN,NaN,Siaya,KE041,Kenya,KE,2017-11-03,2019-10-31,NaN,607.542114
4,Awendo,KE044254,NaN,NaN,NaN,Migori,KE044,Kenya,KE,2017-11-03,2019-10-31,NaN,262.959473
...,...,...,...,...,...,...,...,...,...,...,...,...,...
285,Webuye West,KE039222,NaN,NaN,NaN,Bungoma,KE039,Kenya,KE,2017-11-03,2019-10-31,NaN,236.070190
286,West Mugirango,KE046271,NaN,NaN,NaN,Nyamira,KE046,Kenya,KE,2017-11-03,2019-10-31,NaN,179.822205
287,Westlands,KE047274,NaN,NaN,NaN,Nairobi,KE047,Kenya,KE,2017-11-03,2019-10-31,NaN,72.704254
288,Wundanyi,KE006024,NaN,NaN,NaN,Taita Taveta,KE006,Kenya,KE,2017-11-03,2019-10-31,NaN,850.952271
289,Yatta,KE016076,NaN,NaN,NaN,Machakos,KE016,Kenya,KE,2017-11-03,2019-10-31,NaN,1060.933716